# Generated by Django 4.1.7 on 2023-04-06 13:32

from django.db import migrations, models
import django.db.models.deletion
import shop.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_eco', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=255)),
                ('price', models.IntegerField(validators=[shop.models.not_negative])),
                ('on_sale', models.BooleanField(default=False)),
                ('discount', models.IntegerField(default=0, validators=[shop.models.not_negative])),
                ('final_price', models.IntegerField(default=0, validators=[shop.models.not_negative])),
                ('quantity', models.IntegerField(default=1, validators=[shop.models.not_negative])),
                ('details', models.TextField(blank=True, null=True)),
                ('slug', models.SlugField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ItemBrandSegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_segment', models.CharField(max_length=25, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ItemColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ItemGender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(max_length=30, unique=True)),
                ('slug', models.SlugField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ItemMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ItemPicture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
                ('picture', models.ImageField(upload_to='shop/static/shop/images/')),
            ],
        ),
        migrations.CreateModel(
            name='ItemSeason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ItemSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ItemType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=30, unique=True)),
                ('slug', models.SlugField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ItemStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(validators=[shop.models.not_negative])),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.item')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.itemsize')),
            ],
        ),
        migrations.AddField(
            model_name='itemsize',
            name='item_type',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='shop.itemtype'),
        ),
        migrations.CreateModel(
            name='ItemCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=30, unique=True)),
                ('is_returnable', models.BooleanField(default=True)),
                ('slug', models.SlugField(null=True)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.itemtype')),
            ],
        ),
        migrations.CreateModel(
            name='ItemBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=50, null=True, unique=True)),
                ('logo', models.ImageField(default=None, upload_to='')),
                ('description', models.TextField(default=None, null=True)),
                ('segment', models.ManyToManyField(to='shop.itembrandsegment')),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='item_brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.itembrand'),
        ),
        migrations.AddField(
            model_name='item',
            name='item_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.itemcategory'),
        ),
        migrations.AddField(
            model_name='item',
            name='item_color',
            field=models.ManyToManyField(to='shop.itemcolor'),
        ),
        migrations.AddField(
            model_name='item',
            name='item_gender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.itemgender'),
        ),
        migrations.AddField(
            model_name='item',
            name='item_material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.itemmaterial'),
        ),
        migrations.AddField(
            model_name='item',
            name='item_season',
            field=models.ManyToManyField(to='shop.itemseason'),
        ),
        migrations.AddField(
            model_name='item',
            name='item_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_type', to='shop.itemtype', to_field='type'),
        ),
        migrations.AddField(
            model_name='item',
            name='pictures',
            field=models.ManyToManyField(default=None, to='shop.itempicture'),
        ),
    ]
