# Generated by Django 4.1.7 on 2023-04-11 11:59

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_alter_itemstock_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemstock',
            name='item_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.itemtype'),
        ),
        migrations.AlterField(
            model_name='itemstock',
            name='size',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='item_type', chained_model_field='size', on_delete=django.db.models.deletion.CASCADE, to='shop.itemsize'),
        ),
    ]
