# Generated by Django 4.1.7 on 2023-04-11 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_cart_created_at_cart_updated_at_alter_cart_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemsize',
            name='slug',
            field=models.SlugField(null=True),
        ),
    ]
