# Generated by Django 4.1.7 on 2023-04-11 14:28

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_alter_cart_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='unique_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
