# Generated by Django 4.1.7 on 2023-04-11 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_cart_unique_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='unique_id',
        ),
    ]
