# Generated by Django 4.1.7 on 2023-04-11 14:34

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_cart_unique_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='unique_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True, unique=True),
        ),
    ]
