# Generated by Django 4.1.7 on 2023-04-12 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0018_cart_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='session',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
    ]
