# Generated by Django 4.1.7 on 2023-04-12 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0020_itemincart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemincart',
            name='quantity',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
