# Generated by Django 4.1.7 on 2023-04-12 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0021_alter_itemincart_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemincart',
            name='quantity',
            field=models.PositiveSmallIntegerField(default=0, null=True),
        ),
    ]
